POSTGRES_URL = "postgresql://postgres:postgres@localhost:5432/postgres"

TFIDF_MAX_FEATURES = 1000
TOP_K_SIMILAR_USERS = 5
CB_TOP_SIM = 5

CF_WEIGHT = 0.5
CB_WEIGHT = 0.3
POP_WEIGHT = 0.2

ALS_FACTORS = 50
ALS_REGULARIZATION = 0.1
ALS_ITERATIONS = 20